### PR TITLE
Recipe list and viewer

### PR DESCRIPTION
**Pull request by Tichau**
**This request must be merged after the pull request #9**

This PR contains:
* Add WebRequest package to make api calls
* Add ReactRouter package
* Display the recipes list and a recipe using Markdown.

### CODE REVIEW

**Comment by nadege** [comment]
holy cow, so many commits!
Ok next git lesson will be about interactive rebase and rewriting history!
This branch needs to be rebased on `master` before merging anyway.

**Comment by Tichau** [comment]
I've rebased the branch onto master. It is now a little bit readable :)
What do you want to clean in the history?

**Comment by Tichau** [comment]
I've opened PR #11 that contains a subpart of this PR. 
I will rebase this one after it is merged.

**Comment by Tichau** [comment]
I've rebased it on the merged PR #9. :)

**Pull request merged**
